# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when running `supabase init`.
project_id = "pulsecheck"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[functions.ping-monitors]
verify_jwt = false
