services:

  frontend:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
