services:

  frontend:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-backend:latest
    command: celery -A pulsecheck worker --loglevel=info
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery-beat:
    image: ${DOCKERHUB_USERNAME}/pulsecheck-backend:latest
    command: celery -A pulsecheck beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
