# Generated by Django 5.2.14 on 2026-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_site_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_email', models.EmailField(default='admin@pulsecheck.com', max_length=254)),
            ],
        ),
    ]
