# Generated by Django 5.2.14 on 2026-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='check_interval',
            field=models.IntegerField(default=5),
        ),
    ]
