# Generated by Django 5.2.14 on 2026-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
